<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?php /* @escapeNotVerified *//* @escapeNotVerified */echo $block->getChildHtml('form_before') ?>
<form 
    class="form form-newsletter-manage"
    action="<?php /* @escapeNotVerified */echo $block->escapeUrl($block->getAction()) ?>"
    method="post"
    id="form-validate"
    data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <?php /* @escapeNotVerified */echo $block->getBlockHtml('formkey') ?>
        <legend class="legend">
            <span>
                <?php /* @escapeNotVerified */echo $block->escapeHtml(__('Subscription option')) ?>
            </span>
        </legend><br>
        <div class="field choice">
            <input 
                type="checkbox"
                name="is_subscribed"
                id="subscription"
                value="1"
                title="<?php /* @escapeNotVerified */echo $block->escapeHtml(__('General Subscription')) ?>"
                <?php if ($block->getIsSubscribed()) : ?>
                    checked="checked"
                <?php endif; ?> 
                class="checkbox">
            <label for="subscription" class="label">
                <span>
                    <?php /* @escapeNotVerified */echo $block->escapeHtml(__('General Subscription')) ?>
                </span>
            </label>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php /* @escapeNotVerified */echo $block->getChildHtml('gdpr.checkbox'); ?>
        <?php /* @escapeNotVerified */echo $block->getChildHtml('customer.form.newsletter.extra') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button 
                type="submit"
                title="<?php /* @escapeNotVerified */echo $block->escapeHtml(__('Save')) ?>"
                class="action save primary">
                <span>
                    <?php /* @escapeNotVerified */echo $block->escapeHtml(__('Save')) ?>
                </span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"
                href="<?php /* @escapeNotVerified */echo $block->escapeUrl($block->getBackUrl()) ?>">
                <span>
                    <?php /* @escapeNotVerified */echo $block->escapeHtml(__('Back')) ?>
                </span>
            </a>
        </div>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?php /* @escapeNotVerified */echo $block->getChildHtml('customer.form.newsletter.extra2') ?>